# Generated by Django 5.0 on 2023-12-27 14:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diseases',
            new_name='Disease',
        ),
        migrations.RenameModel(
            old_name='Specialists',
            new_name='Specialist',
        ),
        migrations.RenameModel(
            old_name='Symptoms',
            new_name='Symptom',
        ),
    ]
