# Generated by Django 5.0 on 2024-01-01 13:45

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis_system', '0002_rename_diseases_disease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=django_jsonform.models.fields.JSONField(null=True),
        ),
    ]
