# Generated by Django 5.0 on 2024-01-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis_system', '0003_disease_symptoms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='disease',
            name='symptom1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptom2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptom3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptom4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
