# Generated by Django 5.0 on 2024-01-01 14:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis_system', '0005_alter_disease_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disease',
            new_name='Patient',
        ),
    ]
