# Generated by Django 5.0 on 2024-01-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis_system', '0006_rename_disease_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='disease',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
