# Generated by Django 5.0 on 2024-01-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis_system', '0007_alter_patient_disease'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
