# Generated by Django 5.0 on 2023-12-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='specialities',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
