# Generated by Django 5.0 on 2024-01-01 08:08

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_specialities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='specialities',
            field=django_jsonform.models.fields.JSONField(null=True),
        ),
    ]
